export const FORENSIC_EVENT_TYPES = {
  FINAL_DOCUMENT_REGISTERED: 'FINAL_DOCUMENT_REGISTERED',
  FINAL_DOCUMENT_REMOVED: 'FINAL_DOCUMENT_REMOVED',
  DOCUMENT_HARD_REMOVED: 'DOCUMENT_HARD_REMOVED',
  SIGNATURE_RECORDED: 'SIGNATURE_RECORDED',
  DOCUMENT_CANCELED: 'DOCUMENT_CANCELED',
  VIDEO_ATTACHMENT_UPLOADED: 'VIDEO_ATTACHMENT_UPLOADED',
  VIDEO_ATTACHMENT_ACCESSED: 'VIDEO_ATTACHMENT_ACCESSED',
  VIDEO_ATTACHMENT_REMOVED: 'VIDEO_ATTACHMENT_REMOVED',
  DOCUMENT_EXPIRED: 'DOCUMENT_EXPIRED',
  APR_CREATED: 'APR_CREATED',
  APR_UPDATED: 'APR_UPDATED',
  APR_APPROVED: 'APR_APPROVED',
  APR_FINALIZED: 'APR_FINALIZED',
  APR_NEW_VERSION: 'APR_NEW_VERSION',
} as const;

export type ForensicEventType =
  (typeof FORENSIC_EVENT_TYPES)[keyof typeof FORENSIC_EVENT_TYPES];
